AWSTemplateFormatVersion: "2010-09-09"
Description: "(SA00017) - corporate-credit-rating:                                                                                  
  Solution for training AutoGluon models for corporate credit rating using Amazon SageMaker.
  Version 1"

Parameters:
  SolutionPrefix:
    Type: String
    Default: "sagemaker-soln-ccr-"
    Description: |
      Used to name resources created as part of this stack (and inside nested stacks too).
      Can be the same as the stack name used by AWS CloudFormation, but this field has extra
      constraints because it's used to name resources with restrictions (e.g. Amazon S3 bucket
      names cannot contain capital letters).
    AllowedPattern: '^sagemaker-soln-ccr[a-z0-9\-]{1,20}$'
    ConstraintDescription: |
      Only allowed to use lowercase letters, hyphens and/or numbers.
      Should also start with 'sagemaker-soln-ccr' for permission management.

  SolutionName:
    Description: |
      Prefix for the solution name. Needs to be 'sagemaker-corporate-credit-rating'
      or begin with  'sagemaker-corporate-credit-rating-' followed by a set of letters and hyphens.
      Used to specify a particular directory on S3, that can correspond to a development branch.
    Type: String
    Default: "sagemaker-corporate-credit-rating/1.1.0"
    AllowedPattern: '^sagemaker-corporate-credit-rating(/[0-9]+\.[0-9]+\.[0-9]+-?[a-zA-Z-0-9\.+]*)?$'

  IamRole:
    Type: String
    Default: ""
    Description: |
      IAM Role that will be attached to the resources created by this CloudFormation to grant them permissions to
      perform their required functions. This role should allow SageMaker and Lambda perform the required actions like
      creating training jobs and processing jobs. If left blank, the template will attempt to create a role for you.
      This can cause a stack creation error if you don't have privileges to create new roles.

  SageMakerNotebookInstanceType:
    Description: SageMaker notebook instance type.
    Type: String
    Default: "ml.t3.medium"

  CreateSageMakerNotebookInstance:
    Description: Whether to launch sagemaker notebook instance
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "true"

  StackVersion:
    Description: |
      CloudFormation Stack version.
      Use "release" version unless you are customizing the
      CloudFormation templates and the solution artifacts in S3 bucket
    Type: String
    Default: release
    AllowedValues:
      - release
      - development

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Solution Configuration"
        Parameters:
          - SolutionPrefix
          - SolutionName
          - StackVersion
          - CreateSageMakerNotebookInstance
          - SageMakerNotebookInstanceType
    ParameterLabels:
      SolutionPrefix:
        default: "Solution Resources Name Prefix"
      SolutionName:
        default: "Name of the solution"
      StackVersion:
        default: "Solution Stack Version"
      CreateSageMakerNotebookInstance:
        default: "Launch SageMaker Notebook Instance"
      SageMakerNotebookInstanceType:
        default: "SageMaker Notebook Instance Type"

Conditions:
  CreateClassicSageMakerResources:
    !Equals [!Ref CreateSageMakerNotebookInstance, "true"]
  CreateCustomSolutionRole: !Equals [!Ref IamRole, ""]

Mappings:
  S3:
    release:
      BucketPrefix: "sagemaker-solutions-prod"
    development:
      BucketPrefix: "sagemaker-solutions-devo"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: "Retain"
    Properties:
      BucketName: !Sub "${SolutionPrefix}-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: Configuring logging requires supplying an existing customer S3 bucket to store logs.
          - id: W51
            reason: Default access policy is sufficient.

  SageMakerPermissionsStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateCustomSolutionRole
    Properties:
      TemplateURL: !Sub
        - "https://${SolutionRefBucketBase}-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/${SolutionName}/cloudformation/corporate-credit-rating-permissions.yaml"
        - SolutionRefBucketBase:
            !FindInMap [S3, !Ref StackVersion, BucketPrefix]
      Parameters:
        SolutionPrefix: !Ref SolutionPrefix
        SolutionName: !Ref SolutionName
        S3Bucket: !Ref S3Bucket
        StackVersion: !Ref StackVersion

  SageMakerStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateClassicSageMakerResources
    Properties:
      TemplateURL: !Sub
        - "https://${SolutionRefBucketBase}-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/${SolutionName}/cloudformation/corporate-credit-rating-sagemaker-notebook-instance.yaml"
        - SolutionRefBucketBase:
            !FindInMap [S3, !Ref StackVersion, BucketPrefix]
      Parameters:
        SolutionPrefix: !Ref SolutionPrefix
        SolutionName: !Ref SolutionName
        S3Bucket: !Ref S3Bucket
        SageMakerIAMRoleArn:
          !If [
            CreateCustomSolutionRole,
            !GetAtt SageMakerPermissionsStack.Outputs.SageMakerRoleArn,
            !Ref IamRole,
          ]
        SageMakerNotebookInstanceType: !Ref SageMakerNotebookInstanceType
        StackVersion: !Ref StackVersion

  SageMakerEndpointStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub
        - "https://${SolutionRefBucketBase}-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/${SolutionName}/cloudformation/corporate-credit-rating-endpoint.yaml"
        - SolutionRefBucketBase:
            !FindInMap [S3, !Ref StackVersion, BucketPrefix]
      Parameters:
        SolutionPrefix: !Ref SolutionPrefix
        SolutionName: !Ref SolutionName
        SageMakerIAMRoleArn:
          !If [
            CreateCustomSolutionRole,
            !GetAtt SageMakerPermissionsStack.Outputs.SageMakerRoleArn,
            !Ref IamRole,
          ]
        SolutionRefBucketBase: !FindInMap [S3, !Ref StackVersion, BucketPrefix]

  SolutionAssistantStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub
        - "https://${SolutionRefBucketBase}-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/${SolutionName}/cloudformation/solution-assistant/solution-assistant.yaml"
        - SolutionRefBucketBase:
            !FindInMap [S3, !Ref StackVersion, BucketPrefix]
      Parameters:
        SolutionPrefix: !Ref SolutionPrefix
        SolutionName: !Ref SolutionName
        StackName: !Ref AWS::StackName
        S3Bucket: !Ref S3Bucket
        SolutionS3Bucket: !Sub
          - "${SolutionRefBucketBase}-${AWS::Region}"
          - SolutionRefBucketBase:
              !FindInMap [S3, !Ref StackVersion, BucketPrefix]
        RoleArn:
          !If [
            CreateCustomSolutionRole,
            !GetAtt SageMakerPermissionsStack.Outputs.SageMakerRoleArn,
            !Ref IamRole,
          ]

Outputs:
  SolutionName:
    Value: !Ref SolutionName

  SourceCode:
    Condition: CreateClassicSageMakerResources
    Description: "Open Jupyter IDE. This authenticate you against Jupyter."
    Value: !GetAtt SageMakerStack.Outputs.SourceCode

  NotebookInstance:
    Description: "SageMaker Notebook instance to manually orchestrate data preprocessing, model training and deploying an endpoint"
    Value:
      !If [
        CreateClassicSageMakerResources,
        !GetAtt SageMakerStack.Outputs.SageMakerNotebookInstanceSignOn,
        "",
      ]

  AccountID:
    Description: "AWS Account ID to be passed downstream to the notebook instance"
    Value: !Ref AWS::AccountId

  AWSRegion:
    Description: "AWS Region to be passed downstream to the notebook instance"
    Value: !Ref AWS::Region

  IamRole:
    Description: "Arn of SageMaker Execution Role"
    Value:
      !If [
        CreateCustomSolutionRole,
        !GetAtt SageMakerPermissionsStack.Outputs.SageMakerRoleArn,
        !Ref IamRole,
      ]

  SolutionPrefix:
    Description: "Solution Prefix for naming SageMaker transient resources"
    Value: !Ref SolutionPrefix

  S3Bucket:
    Description: "S3 bucket name used in the solution to store artifacts"
    Value: !Ref S3Bucket

  SolutionS3Bucket:
    Description: "Solution S3 bucket"
    Value: !FindInMap [S3, !Ref StackVersion, BucketPrefix]

  DemoEndpointName:
    Description: "Name of the demo endpoint"
    Value: !GetAtt SageMakerEndpointStack.Outputs.EndpointName

  SageMakerMode:
    Value: !If [CreateClassicSageMakerResources, "NotebookInstance", "Studio"]

  StackName:
    Value: !Ref AWS::StackName
