AWSTemplateFormatVersion: "2010-09-09"
Description: "(SA00017) - corporate-credit-rating
  Solution for training AutoGluon models for corporate credit rating using Amazon SageMaker solution assistant stack.
  Version 1.1.0"

Parameters:
  SolutionPrefix:
    Type: String
  SolutionName:
    Type: String
  StackName:
    Type: String
  S3Bucket:
    Type: String
  SolutionS3Bucket:
    Type: String
  RoleArn:
    Type: String

Mappings:
  Function:
    SolutionAssistant:
      S3Key: "build/solution-assistant.zip"

Resources:
  SolutionAssistant:
    Type: "Custom::SolutionAssistant"
    Properties:
      SolutionPrefix: !Ref SolutionPrefix
      ServiceToken: !GetAtt SolutionAssistantLambda.Arn
      S3Bucket: !Ref S3Bucket
      StackName: !Ref StackName

  SolutionAssistantLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "lambda_fn.handler"
      FunctionName: !Sub "${SolutionPrefix}-solution-assistant"
      Role: !Ref RoleArn
      Runtime: "python3.8"
      Code:
        S3Bucket: !Ref SolutionS3Bucket
        S3Key: !Sub
          - "${SolutionName}/${LambdaS3Key}"
          - LambdaS3Key: !FindInMap [Function, SolutionAssistant, S3Key]
      Timeout: 60
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W58
            reason: >-
              The required permissions are provided in the permissions stack.
